{% set name = "yasa" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92a5445ea7eb29c9b181e15e70d569bcb3872a10bbda01c5b6d1f60dbc44d5f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - seaborn
    - mne-base >=0.20.0
    - numba
    - outdated
    - antropy
    - scikit-learn
    - tensorpac >=0.6.5
    - pyriemann >=0.2.7
    - sleepecg >=0.5.0
    - lspopt
    - ipywidgets
    - joblib
    - lightgbm

test:
  imports:
    - yasa
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check -vvv

about:
  home: https://raphaelvallat.com/yasa
  summary: YASA (Yet Another Spindle Algorithm) is a Python package to analyze polysomnographic sleep recordings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/raphaelvallat/yasa

extra:
  recipe-maintainers:
    - raphaelvallat
    - larsoner
    - hoechenberger
