{% set name = "yasa" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5510b52fdb2b858e5edc449b28f0c6005ec24aec67e667a1bffd4bd70aeee17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - seaborn
    - mne-base >=0.20.0
    - numba
    - outdated
    - antropy
    - scikit-learn
    - tensorpac >=0.6.5
    - pyriemann >=0.2.7
    - sleepecg >=0.5.0
    - lspopt
    - ipywidgets
    - joblib

test:
  imports:
    - yasa
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://raphaelvallat.com/yasa
  summary: YASA (Yet Another Spindle Algorithm) is a Python package to analyze polysomnographic sleep recordings
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/raphaelvallat/yasa

extra:
  recipe-maintainers:
    - raphaelvallat
    - larsoner
    - hoechenberger
